version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    volumes:
      - .:/build
      - /build/node_modules
    depends_on:
      - mysql_server
      - redis

  mysql_server:
    image: mysql:8.0
    env_file: ./.env
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE="${MYSQL_DATABASE}"
      - MYSQL_USER="${MYSQL_USER}"
      - MYSQL_PASSWORD="${MYSQL_PASSWORD}"
      - MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
